application: soundboardr
version: 1
runtime: python
api_version: 1

handlers:
    
- url: /web
  static_dir: web
    
- url: /scripts
  static_dir: scripts
 
- url: /css
  static_dir: css

- url: .*
  script: main.py
